### ISSUE TITLE
Homework API Due Date Not Working

### ISSUE THREAD

**Issue by DeanSellas** [TheSpaceCoder/mySchool#4]
ISSUE: Not allowing events past today

OCCURS: if event is made for a future date

CAUSE: BAD CODE (my fault... for not thinking ahead)

NOTES: I am doing everything to fix this and make the calendar work as intended, I will have a fix by the next commit!

**Comment by DeanSellas** [comment]
PRIORITY: VERY HIGH! (working on a patch as we speak!)

**Comment by DeanSellas** [comment]
FIXED: patched in 009a7f5

**Comment by TheSpaceCoder** [comment]
Second Fix in commit d1e1930
